# Generated by Django 2.1.1 on 2019-04-23 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=400)),
                ('text', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture_URL', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
        migrations.CreateModel(
            name='Linux',
            fields=[
                ('lid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Article')),
            ],
            options={
                'ordering': ('-lid',),
            },
        ),
    ]
