# Generated by Django 2.1.1 on 2019-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='cid',
            field=models.CharField(default=0, max_length=200, primary_key=True, serialize=False),
        ),
    ]
