# Generated by Django 2.1.1 on 2019-04-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20190423_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture_URL',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='all', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
