# Generated by Django 2.1.1 on 2019-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_remove_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
