# Generated by Django 2.1.1 on 2018-10-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='linux',
            name='lid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
