# Generated by Django 2.1.1 on 2019-04-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20190424_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linux',
            name='article',
        ),
        migrations.DeleteModel(
            name='Linux',
        ),
    ]
